--PARTY_ADMIN
CREATE TABLE PARTY_ADMIN (
ADMIN_ID NUMBER(7) NOT NULL, 
ADMIN_NAME VARCHAR2(50), 
ADMIN_PASSWORD VARCHAR2(25) NOT NULL, 
ADMIN_EMAIL VARCHAR2(50) NOT NULL, 
CREATE_DTTM DATE, 
CONSTRAINT ADMIN_PK PRIMARY KEY (ADMIN_ID) ,
CONSTRAINT ADMIN_EMAIl_UNIQUE UNIQUE (ADMIN_EMAIL) 
); 
--DROP TABLE PARTY_ADMIN;

--PARTY_MASTER
CREATE TABLE PARTY_MASTER( 
PARTY_ID NUMBER(7) NOT NULL, 
PARTY_TITLE VARCHAR2(100), 
ADMIN_ID NUMBER(7) NOT NULL,  
VENUE_ADDRESS_1 VARCHAR2(100), 
VENUE_ADDRESS_2 VARCHAR2(100), 
VENUE_CITY VARCHAR2(50), 
VENUE_COUNTRY VARCHAR2(50) NOT NULL, 
VENUE_ZIP VARCHAR2(15), 
INVITER_SIGN VARCHAR2(50), 
TITLE_IMAGE BLOB,  
START_TIME DATE, 
END_TIME DATE, 
INVITATION_MESSAGE VARCHAR2(500), 
PARTY_STATUS NUMBER(3), 
CREATE_DTTM DATE, 
UPDATE_DTTM DATE, 
INVITER_NOTES VARCHAR2(256), 
-- CONSTRAINT ADMIN_FK FOREIGN KEY (ADMIN_ID) REFERENCES PARTY_ADMIN(ADMIN_ID), 
 CONSTRAINT PARTY_PK PRIMARY KEY (PARTY_ID, ADMIN_ID) 
); 
--DROP TABLE PARTY_MASTER;


--PARTY_USER
CREATE TABLE PARTY_USER(
PARTY_ID NUMBER(7) NOT NULL, 
ADMIN_ID NUMBER(7) NOT NULL, 
USER_ID NUMBER(7) NOT NULL, 
ADMIN_FLAG VARCHAR2(1),
USER_NAME VARCHAR2(50), 
USER_EMAIL VARCHAR2(50) NOT NULL, 
USER_STATUS NUMBER(3), 
CREATE_DTTM DATE,
UPDATE_DTTM DATE,
--CONSTRAINT USER_ADMIN_FK FOREIGN KEY (ADMIN_ID) REFERENCES PARTY_ADMIN(ADMIN_ID),
--CONSTRAINT USER_PARTY_FK FOREIGN KEY (PARTY_ID) REFERENCES PARTY_MASTER(PARTY_ID),
CONSTRAINT USER_PK PRIMARY KEY (USER_ID,ADMIN_ID,PARTY_ID)
);
--DROP TABLE PARTY_USER;

--PARTY_ITEMS
CREATE TABLE PARTY_ITEMS (
PARTY_ID NUMBER(7) NOT NULL, 
USER_ID NUMBER(7) NOT NULL, 
CATEG_ID NUMBER(4) NOT NULL, 
SUB_CATEG_ONE_VALUE VARCHAR2(100), 
SUB_CATEG_TWO_VALUE VARCHAR2(100), 
QUANTITY NUMBER(7), 
CREATED_DTTM DATE,
CONSTRAINT ITEM_PK PRIMARY KEY (PARTY_ID,USER_ID,CATEG_ID,SUB_CATEG_ONE_VALUE,SUB_CATEG_TWO_VALUE)
--CONSTRAINT ITEM_USER_FK FOREIGN KEY (USER_ID) REFERENCES PARTY_USER(USER_ID),
--CONSTRAINT ITEM_PARTY_FK FOREIGN KEY (PARTY_ID) REFERENCES PARTY_MASTER(PARTY_ID)
);
--DROP TABLE PARTY_ITEMS;


--CATEGORY_MASTER 
CREATE TABLE CATEGORY_MASTER(
ADMIN_ID NUMBER(7) NOT NULL, 
CATEG_ID  NUMBER(4),
CATEG_NAME  VARCHAR2(25),
SUB_CATEG_ONE VARCHAR2(25), 
SUB_CATEG_TWO VARCHAR2(25), 
UNIT_ID NUMBER(3),
CONSTRAINT CATEGORY_PK PRIMARY KEY (ADMIN_ID, CATEG_ID, CATEG_NAME,SUB_CATEG_ONE,SUB_CATEG_TWO) );
-- drop table CATEGORY_MASTER;

CREATE TABLE UNIT_MASTER(
UNIT_ID  NUMBER(3), 
UNIT_NAME VARCHAR2(25));

CREATE TABLE USER_STATUS_MASTER(
STATUS_CODE NUMBER(3), 
STATUS_DESC VARCHAR2(25));

CREATE TABLE PARTY_STATUS_MASTER(
STATUS_CODE NUMBER(3), 
STATUS_DESC VARCHAR2(25));

CREATE SEQUENCE ADMIN_ID_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1;
CREATE SEQUENCE PARTY_ID_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1;
CREATE SEQUENCE USER_ID_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1;

SELECT PARTY_ID_SEQ.NEXTVAL FROM DUAL;

COMMIT;





