--Roll back scripts
DROP TABLE PARTY_ADMIN;
DROP TABLE PARTY_MASTER;
DROP TABLE PARTY_USER;
DROP TABLE PARTY_ITEMS;
DROP TABLE CATEGORY_MASTER;
DROP TABLE UNIT_MASTER;
DROP TABLE USER_STATUS_MASTER;
DROP TABLE PARTY_STATUS_MASTER;
DROP SEQUENCE ADMIN_ID_SEQ;
DROP SEQUENCE PARTY_ID_SEQ;
DROP SEQUENCE USER_ID_SEQ;

COMMIT;